### ISSUE TITLE
Formulas are broken on the website

### ISSUE THREAD

**Issue by timvink** [DoubleML/doubleml-docs#131]
### Description of the issue or change proposal

All formulas are broekn. For example on [this page](https://docs.doubleml.org/stable/guide/models.html#models):

https://docs.doubleml.org/stable/guide/models.html#models

![image](https://user-images.githubusercontent.com/5570380/232018131-f5eea8d5-f0fa-45d5-ae0d-0ae84048aa16.png)

I'm using a corporate laptop with Windows & MS Edge browser

**Comment by PhilippBach** [comment]
Dear @timvink 

thanks for letting us know about this. Unfortunately, I couldn't replicate the issue (see screenshots below), neither in Firefox nor in Chrome.

![grafik](https://user-images.githubusercontent.com/42535555/232030460-eeb3d204-16c3-4a8f-8c21-13102c39ad5d.png)

I close this issue as I couldn't replicate it. Maybe you can try to use another browser and/or at another time. In case this shows up again, feel free to reopen this

**Comment by timvink** [comment]
Thanks for the fast reply!

Turns out it was a proxy issue, it was not loading the mathjax CDN. Works now 🤷🏻 

```
<script defer="defer" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```
