### ISSUE TITLE
Fix links in FLAML example

### ISSUE THREAD

**Issue by PhilippBach** [DoubleML/doubleml-docs#202]
### Description of the issue or change proposal

Hi @OliverSchacht , 

I think the links in the [FLAML example](https://docs.doubleml.org/dev/examples/py_double_ml_meets_flaml.html) are not nicely formatted. I think in Jupyter, it's not possible to link to codestyle text. It should be either `FLAML` without a link or [FLAML](https://microsoft.github.io/FLAML/) with standard text formatting. 

I open the issue and we'll see who takes care of it first.

**Comment by OliverSchacht** [comment]
Hi @PhilippBach 
yes thank you for pointing that out.
I noticed it too and fixed it with [this commit](https://github.com/DoubleML/doubleml-docs/commit/ac7536575e0730848b98ae97dc7d519aa0b3a526) directly into the dev branch. 
I haven't deployed it yet but I started a deployment run just now.

**Comment by OliverSchacht** [comment]
Looks better now
https://docs.doubleml.org/dev/examples/py_double_ml_meets_flaml.html#DoubleML-meets-FLAML---How-to-tune-learners-automatically-within-DoubleML

**Comment by PhilippBach** [comment]
Yes, thank you! Looks good now!
