### ISSUE TITLE
Copy Button not working properly for R

### ISSUE THREAD

**Issue by SvenKlaassen** [DoubleML/doubleml-docs#36]
Using the Copy Button for the R Code, copies the row numbers, too.

See for example: https://docs.doubleml.org/stable/intro/intro.html

**Comment by MalteKurz** [comment]
Thanks for reporting this. In an older version, it looked like this:
![image](https://user-images.githubusercontent.com/7427117/128006373-17c8d7eb-671f-4bed-b27d-bae81a0fbcf8.png)
 The line numbers where separated (by a vertical line) and the copy-button did work as intended.
Now it looks like this
![image](https://user-images.githubusercontent.com/7427117/128006271-e811e472-05c4-47d5-be0a-28b2244bce64.png)
and the copy-button is no longer working.

I will check which dependency update did cause this change.

**Comment by MalteKurz** [comment]
Tried to track it down. From the github actions history it looks like the root cause is in the following diff of package versions
![Screenshot from 2021-08-03 14-05-33](https://user-images.githubusercontent.com/7427117/128012728-45e8bb6f-b4d7-4796-a45d-bc47aa9d451f.png)

**Comment by MalteKurz** [comment]
Ok it seems like the combination of `Sphinx` in version `>4.0.0` and `jupyter-sphinx` somehow causes this problem. The only solution I found so far is removing the line numbers. I think this should be fine. The functioning of the copy-button is definitely more valuable then line numbers....
